repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=88', '--extend-ignore=E203']

  - repo: local
    hooks:
      - id: check-docstrings
        name: Check Python docstrings
        entry: python scripts/validate_docstrings.py
        language: system
        files: '\.py$'
        pass_filenames: true

      - id: check-type-annotations
        name: Check type annotations
        entry: python scripts/validate_type_annotations.py
        language: system
        files: '\.py$'
        pass_filenames: true

      - id: check-documentation-coverage
        name: Check documentation coverage
        entry: python scripts/check_documentation_coverage.py
        language: system
        files: '\.py$'
        always_run: true

      - id: detect-legacy-patterns
        name: Detect legacy code patterns (ADR-010)
        entry: python scripts/detect_legacy_patterns.py --fail-fast
        language: system
        files: '\.(py|html)$'
        always_run: true